apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flink

resources:
  - base/jobmanager-deployment.yaml
  - base/jobmanager-service.yaml
  - base/taskmanager-deployment.yaml

patches:
  - path: overlays/jobmanager-deployment-patch.yaml
    target:
      kind: Deployment
      name: flink-jobmanager
  - path: overlays/taskmanager-deployment-patch.yaml
    target:
      kind: Deployment
      name: flink-taskmanager

